services:
  client:
    image: pkotchav/client:latest
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: pkotchav/proj-op2-server:latest
    ports:
      - "3000:3000"
